### ISSUE TITLE
Does not work in Contao ^4.4

### ISSUE THREAD

**Issue by sheeep** [1up-lab/contao-cache-warmup#3]
To be precise, with `contao/core-bundle: ^4.4`.
First there is no [jQuery version global](https://github.com/1up-lab/contao-cache-warmup/blob/master/src/CacheWarmup/CacheWarmup.php#L20) anymore.

Furthermore, the path in assets seems to have changed, there is no subfolder core.

```
$GLOBALS['TL_JAVASCRIPT'][] = 'assets/jquery/core/' . $GLOBALS['TL_ASSETS']['JQUERY'] . '/jquery.min.js|static';
```

**Comment by lroovers** [comment]
other files that seems to be moved
jquery.min.js:2 GET ../system/themes/default/images/loading.gif 404 (Not Found)
jquery.min.js:2 GET ..l/system/themes/default/images/help.gif 404 (Not Found)

**Comment by bytehead** [comment]
Yes, default theme now is called `flexible`.

**Comment by akroii** [comment]
Ive testet your latest dev-branch for 4.8
this is what i got, after i clicked on "Warmup cache":
```
An exception occurred while executing 'DELETE FROM tl_session WHERE tstamp<1569333395 OR hash='ceaf2e5ae1731c24c38bb3c1e07b1005dd4ea981'': SQLSTATE[42S02]: Base table or view not found: 1146 Table '26-w35gbmh.tl_session' doesn't exist
```

Contao Manager :
![Bildschirmfoto 2019-09-24 um 16 56 18](https://user-images.githubusercontent.com/8830861/65523386-7ea68080-deec-11e9-8731-40795271b39b.png)

**Comment by bytehead** [comment]
The table `tl_session` does not exist anymore in Contao 4.8. Needs to be fixed.

**Comment by bytehead** [comment]
@akroii can you try again? I removed the table access in faeb2b6.

**Comment by akroii** [comment]
I've replaced your code and i still got the same error:

```
An exception occurred while executing 'DELETE FROM tl_session WHERE tstamp<1569339549 OR hash='ba9bb11807f5f30cb90e214e0516a06cfb471ecd'': SQLSTATE[42S02]: Base table or view not found: 1146 Table '26-w35gbmh.tl_session' doesn't exist
```

**Comment by bytehead** [comment]
Did you run `composer update`?

**Comment by bytehead** [comment]
> Contao Manager :
> ![Bildschirmfoto 2019-09-24 um 16 56 18](https://user-images.githubusercontent.com/8830861/65523386-7ea68080-deec-11e9-8731-40795271b39b.png)

you'll have to use the contao 4 branch: `dev-feature/contao-4`

**Comment by akroii** [comment]
It looks good. Thanks a lot!
<img width="470" alt="Bildschirmfoto 2019-09-24 um 19 27 08" src="https://user-images.githubusercontent.com/8830861/65535392-989e8e00-df01-11e9-9b23-37e8c5569bc4.png">

**Comment by akroii** [comment]
Is there a way to prove it? I will check that cache is really created

Edit: i've checked it by myself. var/cache/prod was successfully created. http_cache contains pages 😙

**Comment by bytehead** [comment]
This extension will be obsolete in Contao 4.9 anyway 😄

**Comment by akroii** [comment]
looking forward to get more infos about that 😊

**Comment by bytehead** [comment]
https://contao.org/de/news/rueckblick-auf-das-zweite-core-entwicklertreffen-2019.html 😎
