### ISSUE TITLE
Scripts takes also disabled pages

### ISSUE THREAD

**Issue by lroovers** [1up-lab/contao-cache-warmup#5]
I would expect that pages that are 'hidden' or 'disabled'  would not be part of the warmup process.

Is this a bug or did I miss a setting?

**Comment by bytehead** [comment]
Disabled should not, but hidden pages should also be warmed up. I'll have to check.

**Comment by lroovers** [comment]
And what about the pages that where 'excluded from sitemap' ?

point is basically that I see lot of pages that cannot be accessed (404 notice)

and I did not assign / limit access any page to a user or usergroep

**Comment by bytehead** [comment]
The extensions checks both, sitemap and page tree for pages to warm up.

**Comment by bytehead** [comment]
It actually doesn't matter if it returns a 404, it tries just to warmup the cache. I see no malfunction there.
